apiVersion: v1
kind: Service
metadata:
  name: file-storage-service
  labels:
    app: file-storage-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: file-storage-service