apiVersion: v1
kind: Service
metadata:
  name: job-search-service
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: job-search-service
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http