apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microservices-infra
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: notification-service