apiVersion: v1
kind: Service
metadata:
  name: resume-management-service
  labels:
    app: resume-management
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: resume-management
