apiVersion: v1
kind: Service
metadata:
  name: resume-generation-service
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: resume-generation-service