apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: your-docker-repo/config-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_DB_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: config_db_uri
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      imagePullSecrets:
      - name: regcred