apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-search-service
  labels:
    app: job-search-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-search-service
  template:
    metadata:
      labels:
        app: job-search-service
    spec:
      containers:
      - name: job-search-service
        image: your-docker-repo/job-search-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database_url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis_url
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      imagePullSecrets:
      - name: regcred