apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-management-service
  labels:
    app: resume-management-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume-management-service
  template:
    metadata:
      labels:
        app: resume-management-service
    spec:
      containers:
        - name: resume-management-service
          image: your-docker-repo/resume-management-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: database-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-url
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"