apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-orchestrator
  labels:
    app: workflow-orchestrator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workflow-orchestrator
  template:
    metadata:
      labels:
        app: workflow-orchestrator
    spec:
      containers:
      - name: workflow-orchestrator
        image: your-docker-repo/workflow-orchestrator:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database_url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis_url
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      imagePullSecrets:
      - name: regcred